"""remove unique slot_id from appointments

Revision ID: 8eef669a2e9f
Revises: f83721b1d320
Create Date: 2026-08-10 13:52:25.515296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eef669a2e9f'
down_revision: Union[str, None] = 'f83721b1d320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_slot_id_key', 'appointments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('appointments_slot_id_key', 'appointments', ['slot_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###