"""add slot_duration to schedule_templates

Revision ID: f1d75e08d6dc
Revises: 8eef669a2e9f
Create Date: 2026-08-14 09:17:17.554371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d75e08d6dc'
down_revision: Union[str, None] = '8eef669a2e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_templates', sa.Column('slot_duration', sa.Integer(), nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_templates', 'slot_duration')
    # ### end Alembic commands ###